version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  discovery-service:
    build: ./Discovery
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - server.port=8761
      - spring.application.name=discovery-service
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  product-service:
    build: ./product
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - server.port=8082
      - spring.application.name=product-service

      # DB
      - spring.datasource.url=jdbc:postgresql://postgres:5432/product_db
      - spring.datasource.username=order_user
      - spring.datasource.password=password

      # Kafka
      - spring.kafka.bootstrap-servers=kafka:9092

      # Redis
      - spring.data.redis.host=redis
      - spring.data.redis.port=6379

      # Eureka
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

      # Zipkin
      - management.tracing.sampling.probability=1.0
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

  order-service:
    build: ./Orders
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      - server.port=8081
      - spring.application.name=order-service

      # DB
      - spring.datasource.url=jdbc:postgresql://postgres:5432/order_db
      - spring.datasource.username=order_user
      - spring.datasource.password=password

      # Kafka
      - spring.kafka.bootstrap-servers=kafka:9092

      # Eureka
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

      # Zipkin
      - management.tracing.sampling.probability=1.0
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

  gateway-service:
    build: ./Gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      discovery-service:
        condition: service_healthy
      order-service:
        condition: service_started
      product-service:
        condition: service_started
    environment:
      - server.port=8080
      - spring.application.name=api-gateway
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

volumes:
  postgres-data: