spring.application.name=product-service

server.port=8082

spring.datasource.url=jdbc:postgresql://postgres:5432/product_db
spring.datasource.username=order_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

eureka.instance.prefer-ip-address=true

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=product-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false 
# Disable type headers to avoid deserialization issues we can use different topics for different event types or include type information in the payload no need to create common package for events
spring.kafka.consumer.properties.spring.json.value.default.type=com.flowcart.product.Events.OrderEvents

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer