spring.application.name=Gateway
server.port=8080
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

 
# /* For debugging purposes, you can set the logging level to DEBUG for Spring Cloud Gateway */
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans