spring.application.name=Discovery
server.port=8761


eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# // The above properties are set to false because this application is the Eureka Server itself, and it does not need to register with another Eureka Server or fetch the registry from another server.